### ISSUE TITLE
TypeError when remote_resolve is disabled

### ISSUE THREAD

**Issue by Noctem** [nibrag/aiosocks#15]
When remote_resolve is disabled, a `TypeError` occurs [here](https://github.com/nibrag/aiosocks/blob/v0.2.3/aiosocks/connector.py#L80) because *aiohttp* returns an islice which it erroneously tries to access by index.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 637, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 378, in connect
    proto = yield from self._create_connection(req)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 685, in _create_connection
    _, proto = yield from self._create_proxy_connection(req)
  File "/usr/local/lib/python3.6/site-packages/aiosocks/connector.py", line 70, in _create_proxy_connection
    return await self._create_socks_connection(req)
  File "/usr/local/lib/python3.6/site-packages/aiosocks/connector.py", line 80, in _create_socks_connection
    dst = dst_hosts[0]['host'], dst_hosts[0]['port']
TypeError: 'itertools.islice' object is not subscriptable
```

**Comment by nibrag** [comment]
Fixed https://github.com/nibrag/aiosocks/pull/16
thanks
