### ISSUE TITLE
Missing argument in exception

### ISSUE THREAD

**Issue by waldanbridger** [nibrag/aiosocks#19]
Failed when connecting to a broken socks5 proxy with aiohttp:

```
session = aiohttp.ClientSession(
    connector=ProxyConnector(remote_resolve=False),
    request_class=ProxyClientRequest,
    headers={'User-Agent': user_agent}
)
auth = aiosocks.Socks5Auth(login, password=password)
response = await session.get(url, params=params, proxy=proxy_addr, proxy_auth=auth)
```

```
Traceback (most recent call last):
  File "/root/vktools/env/lib/python3.6/site-packages/vktools/utils/command.py", line 29, in worker
    loop.run_until_complete(coro_f(*args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/root/vktools/env/lib/python3.6/site-packages/vktools/cli.py", line 78, in run_group_finder
    vk_session_pool = await vktools.api.create_pool(accounts)
  File "/root/vktools/env/lib/python3.6/site-packages/vktools/api/__init__.py", line 49, in create_pool
    await session.authorize(acc['login'], acc['password'], scope='offline')
  File "/root/vktools/env/lib/python3.6/site-packages/vktools/api/session.py", line 81, in authorize
    doc = await self.get_auth_page(scope)
  File "/root/vktools/env/lib/python3.6/site-packages/vktools/api/session.py", line 116, in get_auth_page
    status, resp_text = await self._driver.get(self.AUTH_URL, params=params)
  File "/root/vktools/env/lib/python3.6/site-packages/vktools/api/drivers.py", line 65, in get
    proxy=self.proxy, proxy_auth=self.auth)
  File "/root/vktools/env/lib/python3.6/site-packages/aiohttp/helpers.py", line 104, in __await__
    ret = yield from self._coro
  File "/root/vktools/env/lib/python3.6/site-packages/aiohttp/client.py", line 269, in _request
    conn = yield from self._connector.connect(req)
  File "/root/vktools/env/lib/python3.6/site-packages/aiohttp/connector.py", line 393, in connect
    proto = yield from self._create_connection(req)
  File "/root/vktools/env/lib/python3.6/site-packages/aiohttp/connector.py", line 738, in _create_connection
    _, proto = yield from self._create_proxy_connection(req)
  File "/root/vktools/env/lib/python3.6/site-packages/aiosocks/connector.py", line 70, in _create_proxy_connection
    return await self._create_socks_connection(req)
  File "/root/vktools/env/lib/python3.6/site-packages/aiosocks/connector.py", line 108, in _create_socks_connection
    raise aiohttp.ClientProxyConnectionError(*exc.args)
TypeError: __init__() missing 1 required positional argument: 'os_error'
```

**Comment by nibrag** [comment]
Fixed https://github.com/nibrag/aiosocks/pull/21
