### ISSUE TITLE
Does not work it

### ISSUE THREAD

**Issue by sonfiree** [nibrag/aiosocks#33]
My code
```
import asyncio
import aiohttp
import aiosocks
from aiosocks.connector import ProxyConnector, ProxyClientRequest
```
Error:
```
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\aiosocks\connector.py", line 4, in <module>
    from aiohttp.client_exceptions import certificate_errors, ssl_errors
ImportError: cannot import name 'certificate_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asds.py", line 4, in <module>
    from aiosocks.connector import ProxyConnector, ProxyClientRequest
  File "F:\Anaconda3\lib\site-packages\aiosocks\connector.py", line 6, in <module>
    raise ImportError('aiosocks.SocksConnector require aiohttp library')
ImportError: aiosocks.SocksConnector require aiohttp library
```

What to do?

**Comment by xinhuang** [comment]
`aiohttp` changed the names to `cert_errors`. Need a fix.

**Comment by 0xn0ne** [comment]
It seems that the author is no longer here. God bless.

**Comment by nibrag** [comment]
fixed

**Comment by CallCoders** [comment]
Have the same problem.
Install aiosocks by:
`pip install aiosocks`

Then try to update by:
```
git clone git@github.com:nibrag/aiosocks.git
cd aiosocks
python setup.py install
```
But again:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/tmp/aiowriter.py", line 13, in <module>
    from aiosocks.connector import ProxyConnector, ProxyClientRequest
  File "/Users/admin/tmp/venv/lib/python3.7/site-packages/aiosocks/connector.py", line 6, in <module>
    raise ImportError('aiosocks.SocksConnector require aiohttp library')
ImportError: aiosocks.SocksConnector require aiohttp library
```
line 13: `from aiosocks.connector import ProxyConnector, ProxyClientRequest`

**Comment by SmileyJames** [comment]
I don't think the fix has been published to pip?

**Comment by mikeck1** [comment]
Why is this closed?  Upload changes to pip first.

**Comment by Leezj9671** [comment]
This fix hasn't been published to pip, so install like below:
`pip install git+https://github.com/nibrag/aiosocks`

**Comment by mewforest** [comment]
> This fix hasn't been published to pip, so install like below:
> `pip install git+https://github.com/nibrag/aiosocks`

Please publish changes to pip 🙏

**Comment by cheditx** [comment]
lol why is this closed, is 2023 and the bug is still here
