### ISSUE TITLE
Https and aiosocks not work if use uvloop

### ISSUE THREAD

**Issue by Dexus77** [nibrag/aiosocks#4]
Http + aisocks + uvloop + aiohttp - OK
HttpS + aisocks + uvloop + aiohttp - Fail
aiohttp - 1.0.3
uvloop - 0.5.4
asyncio - 3.4.3

source_traceback: Object created at (most recent call last):
  File "./test.py", line 478, in <module>
    loop.run_until_complete(main())
  File "/usr/local/python/3.5.1/lib/python3.5/site-packages/aiosocks/protocols.py", line 106, in connection_made
    super().connection_made(transport)
  File "/usr/local/python/3.5.1/lib/python3.5/asyncio/streams.py", line 228, in connection_made
    self._loop.create_task(res)
Traceback (most recent call last):
  File "uvloop/task.pyx", line 126, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:99441)
  File "/usr/local/python/3.5.1/lib/python3.5/site-packages/aiosocks/protocols.py", line 80, in negotiate
    self._transport._closing = True
AttributeError: attribute '_closing' of 'uvloop.loop.UVBaseTransport' objects is not writable

**Comment by nibrag** [comment]
http://bugs.python.org/issue23749.
It is possible to fix in python 3.7.

**Comment by Dexus77** [comment]
OK. Sorry, I did not know about this bug. 
Thanks for aisocks!

**Comment by NotSoSuper** [comment]
Any updates on this?

**Comment by nibrag** [comment]
@NotSoSuper 
It is necessary to wait for the appearance of a new api `starttls` in asyncio.

**Comment by nibrag** [comment]
fixed
https://github.com/nibrag/aiosocks/pull/22
