### ISSUE TITLE
ImportError: aiosocks.SocksConnector require aiohttp library

### ISSUE THREAD

**Issue by joeyorlando** [nibrag/aiosocks#40]
- `aiohttp`  = 3.6.2
- `aiosocks` = 0.2.6

```
Traceback (most recent call last):
  File "/Users/joey.orlando/.pyenv/versions/standout_specialties_data_scraping-3.7.0/lib/python3.7/site-packages/aiosocks/connector.py", line 4, in <module>
    from aiohttp.client_exceptions import certificate_errors, ssl_errors
ImportError: cannot import name 'certificate_errors' from 'aiohttp.client_exceptions' (/Users/joey.orlando/.pyenv/versions/standout_specialties_data_scraping-3.7.0/lib/python3.7/site-packages/aiohttp/client_exceptions.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "step2.py", line 13, in <module>
    from aiosocks.connector import ProxyConnector, ProxyClientRequest
  File "/Users/joey.orlando/.pyenv/versions/standout_specialties_data_scraping-3.7.0/lib/python3.7/site-packages/aiosocks/connector.py", line 6, in <module>
    raise ImportError('aiosocks.SocksConnector require aiohttp library')
ImportError: aiosocks.SocksConnector require aiohttp library
```

**Comment by SmileyJames** [comment]
I am experiencing the same error.
failing on
```
  File "/home/jotoole/.local/lib/python3.6/site-packages/aiosocks/connector.py", line 4, in <module>
    from aiohttp.client_exceptions import certificate_errors, ssl_errors

ImportError: cannot import name 'certificate_errors'

```
I've confirmed that I can import
```
from aiohttp.client_exceptions import ssl_errors
```

**Comment by andreasbank** [comment]
This is solved on master. To come around it on 2.6 just search and replace "certificate_errors" with "cert_errors" in connector.py

**Comment by leadscloud** [comment]
代码好多年没更新了，现在不适应新版本了。pip 安装后的无法在新版aiohttp中使用
