### ISSUE TITLE
PyPI Package Broken

### ISSUE THREAD

**Issue by NotSoSuper** [nibrag/aiosocks#9]
Looks like the setup.py on the PyPI package is broken

```
pip3.6 install -U aiosocks
Collecting aiosocks
  Downloading aiosocks-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/aiosocks.egg-info
    writing pip-egg-info/aiosocks.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/aiosocks.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/aiosocks.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/aiosocks.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/aiosocks.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/aiosocks.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_fxbxjzi/aiosocks/setup.py", line 38, in <module>
        s
    NameError: name 's' is not defined

```
There's no line 38 in the current commit so it was probs a mistake.

**Comment by nibrag** [comment]
Fixed, thanks!
